export interface ScoreEntry {
  Family: string;
  Score: number;
}

export interface FamilyDataStructure {
  [key: string]: ScoreEntry[];
}

export const familyData: FamilyDataStructure = {
    BMWP: [
      { Family: 'Heptageniidae', Score: 10 },
      { Family: 'Leptophlebiidae', Score: 10 },
      { Family: 'Ephemerellidae', Score: 10 },
      { Family: 'Potamanthidae', Score: 10 },
      { Family: 'Ephemeridae', Score: 10 },
      { Family: 'Taeniopterygidae', Score: 10 },
      { Family: 'Leuctridae', Score: 10 },
      { Family: 'Capniidae', Score: 10 },
      { Family: 'Perlodidae', Score: 10 },
      { Family: 'Perlidae', Score: 10 },
      { Family: 'Chloroperlidae', Score: 10 },
      { Family: 'Aphelocheiridae', Score: 10 },
      { Family: 'Phryganeidae', Score: 10 },
      { Family: 'Molannidae', Score: 10 },
      { Family: 'Beraeidae', Score: 10 },
      { Family: 'Odontoceridae', Score: 10 },
      { Family: 'Leptoceridae', Score: 10 },
      { Family: 'Goeridae', Score: 10 },
      { Family: 'Lepidostomatidae', Score: 10 },
      { Family: 'Brachycentridae', Score: 10 },
      { Family: 'Sericostomatidae', Score: 10 },
      { Family: 'Astacidae', Score: 8 },
      { Family: 'Lestidae', Score: 8 },
      { Family: 'Agriidae', Score: 8 },
      { Family: 'Gomphidae', Score: 8 },
      { Family: 'Cordulegasteridae', Score: 8 },
      { Family: 'Aeshnidae', Score: 8 },
      { Family: 'Corduliidae', Score: 8 },
      { Family: 'Libellulidae', Score: 8 },
      { Family: 'Psychomyiidae', Score: 8 },
      { Family: 'Philopotamidae', Score: 8 },
      { Family: 'Caenidae', Score: 7 },
      { Family: 'Nemouridae', Score: 7 },
      { Family: 'Rhyacophilidae', Score: 7 },
      { Family: 'Polycentropodidae', Score: 7 },
      { Family: 'Limnephilidae', Score: 7 },
      { Family: 'Neritidae', Score: 6 },
      { Family: 'Viviparidae', Score: 6 },
      { Family: 'Ancylidae', Score: 6 },
      { Family: 'Hydroptilidae', Score: 6 },
      { Family: 'Unionidae', Score: 6 },
      { Family: 'Corophiidae', Score: 6 },
      { Family: 'Gammaridae', Score: 6 },
      { Family: 'Platycnemididae', Score: 6 },
      { Family: 'Coenagriidae', Score: 6 },
      { Family: 'Mesovelidae', Score: 5 },
      { Family: 'Hydrometridae', Score: 5 },
      { Family: 'Gerridae', Score: 5 },
      { Family: 'Nepidae', Score: 5 },
      { Family: 'Naucoridae', Score: 5 },
      { Family: 'Notonectidae', Score: 5 },
      { Family: 'Pleidae', Score: 5 },
      { Family: 'Corixidae', Score: 5 },
      { Family: 'Haliplidae', Score: 5 },
      { Family: 'Hygrobiidae', Score: 5 },
      { Family: 'Dytiscidae', Score: 5 },
      { Family: 'Gyrinidae', Score: 5 },
      { Family: 'Hydrophilidae', Score: 5 },
      { Family: 'Clambidae', Score: 5 },
      { Family: 'Helodidae', Score: 5 },
      { Family: 'Dryopidae', Score: 5 },
      { Family: 'Elminthidae', Score: 5 },
      { Family: 'Chrysomelidae', Score: 5 },
      { Family: 'Curculionidae', Score: 5 },
      { Family: 'Hydropsychidae', Score: 5 },
      { Family: 'Tipulidae', Score: 5 },
      { Family: 'Simuliidae', Score: 5 },
      { Family: 'Planariidae', Score: 5 },
      { Family: 'Dendrocoelidae', Score: 5 },
      { Family: 'Baetidae', Score: 4 },
      { Family: 'Sialidae', Score: 4 },
      { Family: 'Piscicolidae', Score: 4 },
      { Family: 'Valvatidae', Score: 3 },
      { Family: 'Hydrobiidae', Score: 3 },
      { Family: 'Lymnaeidae', Score: 3 },
      { Family: 'Physidae', Score: 3 },
      { Family: 'Planorbidae', Score: 3 },
      { Family: 'Sphaeriidae', Score: 3 },
      { Family: 'Glossiphoniidae', Score: 3 },
      { Family: 'Hirudidae', Score: 3 },
      { Family: 'Erpobdellidae asellidae', Score: 3 },
      { Family: 'Chironomidae', Score: 2 },
      { Family: 'Oligochaeta', Score: 1 }
    ],
    BMWP_My: [
      { Family: 'Caenidae', Score: 4 },
      { Family: 'Ephemerellidae', Score: 5 },
      { Family: 'Ephemeridae', Score: 6 },
      { Family: 'Heptageniidae', Score: 6 },
      { Family: 'Isonychidae', Score: 7 },
      { Family: 'Leptophlebiidae', Score: 6 },
      { Family: 'Neoephemeridae', Score: 7 },
      { Family: 'Potamanthidae', Score: 6 },
      { Family: 'Prosopistomatidae', Score: 8 },
      { Family: 'Tricorythidae', Score: 5 },
      { Family: 'Aeshnidae', Score: 8 },
      { Family: 'Amphipterygidae', Score: 5 },
      { Family: 'Calopterygidae', Score: 7 },
      { Family: 'Chlorocyphidae', Score: 5 },
      { Family: 'Chlorogomphidae', Score: 9 },
      { Family: 'Coenagrionidae', Score: 5 },
      { Family: 'Cordullidae', Score: 6 },
      { Family: 'Euphaeidae', Score: 6 },
      { Family: 'Gomphidae', Score: 5 },
      { Family: 'Libellulidae', Score: 5 },
      { Family: 'Platycnemididae', Score: 5 },
      { Family: 'Platystictidae', Score: 5 },
      { Family: 'Protoneuridae', Score: 7 },
      { Family: 'Nemouridae', Score: 9 },
      { Family: 'Peltoperlidae', Score: 6 },
      { Family: 'Perlidae', Score: 6 },
      { Family: 'Aphelocheridae', Score: 8 },
      { Family: 'Corixidae', Score: 6 },
      { Family: 'Gerridae', Score: 5 },
      { Family: 'Helotrephidae', Score: 6 },
      { Family: 'Leptopodidae', Score: 6 },
      { Family: 'Naucoridae', Score: 6 },
      { Family: 'Notonectidae', Score: 5 },
      { Family: 'Pleidae', Score: 5 },
      { Family: 'Veliidae', Score: 6 },
      { Family: 'Corydalidae', Score: 7 },
      { Family: 'Sialidae', Score: 5 },
      { Family: 'Apataniidae', Score: 7 },
      { Family: 'Calamoceratidae', Score: 5 },
      { Family: 'Ecnomidae', Score: 7 },
      { Family: 'Glossosomatidae', Score: 5 },
      { Family: 'Helicopsychidae', Score: 7 },
      { Family: 'Hydropsychidae', Score: 5 },
      { Family: 'Lepidostomatidae', Score: 9 },
      { Family: 'Leptoceridae', Score: 6 },
      { Family: 'Odontoceridae', Score: 8 },
      { Family: 'Philopotamidae', Score: 6 },
      { Family: 'Polycentropodidae', Score: 5 },
      { Family: 'Sericostomatidae', Score: 5 },
      { Family: 'Stenopsychidae', Score: 6 },
      { Family: 'Xiphocentronidae', Score: 5 },
      { Family: 'Pyralidae', Score: 5 },
      { Family: 'Chrysomalidae', Score: 5 },
      { Family: 'Dryopidae', Score: 6 },
      { Family: 'Dystictidae', Score: 6 },
      { Family: 'Elmidae', Score: 5 },
      { Family: 'Eulicadidae', Score: 7 },
      { Family: 'Gyrinidae', Score: 5 },
      { Family: 'Haliplidae', Score: 5 },
      { Family: 'Hydraenidae', Score: 5 },
      { Family: 'Hydrochidae', Score: 7 },
      { Family: 'Hydrophilidae', Score: 6 },
      { Family: 'Hydroscapidae', Score: 5 },
      { Family: 'Lampyridae', Score: 6 },
      { Family: 'Noteridae', Score: 4 },
      { Family: 'Psephenidae', Score: 5 },
      { Family: 'Ptilodactylidae', Score: 7 },
      { Family: 'Scirtidae', Score: 6 },
      { Family: 'Athericidae', Score: 5 },
      { Family: 'Ceratopogonidae', Score: 6 },
      { Family: 'Chironomidae', Score: 1 },
      { Family: 'Dolichopodidae', Score: 7 },
      { Family: 'Empididae', Score: 7 },
      { Family: 'Sciomyzidae', Score: 5 },
      { Family: 'Simuliidae', Score: 5 },
      { Family: 'Stratiomyidae', Score: 5 },
      { Family: 'Syrphidae', Score: 1 },
      { Family: 'Tabanidae', Score: 5 },
      { Family: 'Tanyderidae', Score: 5 },
      { Family: 'Tipulidae', Score: 6 },
    ],
    BMWP_Thai: [
      { Family: 'Oligochaeta', Score: 1 },
      { Family: 'Erpobdellidae', Score: 3 },
      { Family: 'Glossiphoniidae', Score: 3 },
      { Family: 'Hirudinidae', Score: 3 },
      { Family: 'Piscicolidae', Score: 4 },
      { Family: 'Corbiculidae', Score: 3 },
      { Family: 'Sphaeriidae', Score: 3 },
      { Family: 'Hydrobiidae', Score: 3 },
      { Family: 'Thiaridae', Score: 3 },
      { Family: 'Viviparidae', Score: 6 },
      { Family: 'Ancylidae', Score: 6 },
      { Family: 'Lymnaeidae', Score: 3 },
      { Family: 'Planorbidae', Score: 3 },
      { Family: 'Atyidae', Score: 8 },
      { Family: 'Palaemonidae', Score: 8 },
      { Family: 'Parathelphusidae', Score: 3 },
      { Family: 'Corydalidae', Score: 4 },
      { Family: 'Sialidae', Score: 4 },
      { Family: 'Baetidae', Score: 4 },
      { Family: 'Siphlonuridae', Score: 4 },
      { Family: 'Caenidae', Score: 7 },
      { Family: 'Ephemerellidae', Score: 10 },
      { Family: 'Ephemeridae', Score: 10 },
      { Family: 'Heptageniidae', Score: 10 },
      { Family: 'Leptophlebiidae', Score: 10 },
      { Family: 'Potamanthidae', Score: 10 },
      { Family: 'Aeshnidae', Score: 6 },
      { Family: 'Calopterygidae (agriidae)', Score: 6 },
      { Family: 'Chlorocyphidae', Score: 6 },
      { Family: 'Coenagriidae', Score: 6 },
      { Family: 'Platycnemididae', Score: 6 },
      { Family: 'Corduliidae', Score: 6 },
      { Family: 'Libellulidae', Score: 6 },
      { Family: 'Cordulegastridae', Score: 6 },
      { Family: 'Gomphidae', Score: 6 },
      { Family: 'Macromiidae', Score: 6 },
      { Family: 'Protoneuridae', Score: 3 },
      { Family: 'Nemouridae', Score: 7 },
      { Family: 'Perlidae', Score: 10 },
      { Family: 'Aphelocheiridae', Score: 10 },
      { Family: 'Corixidae', Score: 5 },
      { Family: 'Gerridae', Score: 5 },
      { Family: 'Hydrometridae', Score: 5 },
      { Family: 'Mesoveliidae', Score: 5 },
      { Family: 'Naucoridae', Score: 5 },
      { Family: 'Nepidae', Score: 5 },
      { Family: 'Notonectidae', Score: 5 },
      { Family: 'Pleidae', Score: 5 },
      { Family: 'Veliidae', Score: 5 },
      { Family: 'Goeridae', Score: 10 },
      { Family: 'Hydropsychidae', Score: 5 },
      { Family: 'Arctopsychidae', Score: 5 },
      { Family: 'Hydroptilidae', Score: 6 },
      { Family: 'Lepidostomatidae', Score: 10 },
      { Family: 'Leptoceridae', Score: 10 },
      { Family: 'Molannidae', Score: 10 },
      { Family: 'Odontoceridae', Score: 10 },
      { Family: 'Brachycentridae', Score: 10 },
      { Family: 'Philopotamidae', Score: 8 },
      { Family: 'Phryganeidae', Score: 10 },
      { Family: 'Polycentropodidae', Score: 7 },
      { Family: 'Stenopsychidae', Score: 7 },
      { Family: 'Dipseudopsidae', Score: 7 },
      { Family: 'Psychomyiidae', Score: 8 },
      { Family: 'Rhyacophilidae', Score: 7 },
      { Family: 'Chrysomelidae', Score: 5 },
      { Family: 'Curculionidae', Score: 5 },
      { Family: 'Dryopidae', Score: 5 },
      { Family: 'Dytiscidae', Score: 5 },
      { Family: 'Elminthidae', Score: 5 },
      { Family: 'Gyrinidae', Score: 5 },
      { Family: 'Haliplidae', Score: 5 },
      { Family: 'Helodidae', Score: 5 },
      { Family: 'Hydrophilidae', Score: 5 },
      { Family: 'Psephenidae', Score: 5 },
      { Family: 'Chironomidae', Score: 2 },
      { Family: 'Simuliidae', Score: 5 },
      { Family: 'Tipulidae', Score: 5 }
    ],
    GRSbios: [
      { Family: 'Aeshnidae', Score: 6 },
      { Family: 'Alboglossiphonia heteroclita', Score: 4 },
      { Family: 'Alboglossiphonia hyalina', Score: 5 },
      { Family: 'Alboglossiphonia pahariensis  n. sp.', Score: 5 },
      { Family: 'Alboglossiphonia shillongensis n. sp.', Score: 5 },
      { Family: 'Alboglossiphonia weberi', Score: 4 },
      { Family: 'Allonais inaequalis', Score: 5 },
      { Family: 'Allonais paraguayensis', Score: 5 },
      { Family: 'Amynthas corticis', Score: 7 },
      { Family: 'Amblemidae', Score: 7 },
      { Family: 'Ampullariidae', Score: 4 },
      { Family: 'Ancylidae', Score: 6 },
      { Family: 'Apataniidae', Score: 9 },
      { Family: 'Aphelocheiridae', Score: 7 },
      { Family: 'Arcidae', Score: 8 },
      { Family: 'Asiaticobdella birmanica birmanica', Score: 5 },
      { Family: 'Asiaticobdella birmanica punyamataensis n. ssp.', Score: 7 },
      { Family: 'Asiaticobdella fuscolineata', Score: 5 },
      { Family: 'Assiminea francesiae', Score: 6 },
      { Family: 'Assimineidae', Score: 6 },
      { Family: 'Athericidae', Score: 9 },
      { Family: 'Atyidae', Score: 6 },
      { Family: 'Aulodrilus limnobius', Score: 9 },
      { Family: 'Aulodrilus pigueti', Score: 6 },
      { Family: 'Aulodrilus pluriseta', Score: 6 },
      { Family: 'Aulodrilus remex', Score: 4 },
      { Family: 'Aulophorus furcatus', Score: 7 },
      { Family: 'Aulophorus hymanae', Score: 8 },
      { Family: 'Aulophorus indicus', Score: 7 },
      { Family: 'Baetidae', Score: 6 },
      { Family: 'Baetidae(baetiella sp.)', Score: 7 },
      { Family: 'Baetidae (baetis sp.)', Score: 7 },
      { Family: 'Barbronia nepalensis meghalayaensis n. ssp.', Score: 3 },
      { Family: 'Barbronia nepalensis nepalensis n. sp.', Score: 3 },
      { Family: 'Barbronia weberi', Score: 4 },
      { Family: 'Barythelphusa lugubris', Score: 5 },
      { Family: 'Batracobdelloides reticulatus', Score: 4 },
      { Family: 'Belostomatidae', Score: 6 },
      { Family: 'Bellamya (filopaludina) bengalensis', Score: 6 },
      { Family: 'Bithyniidae', Score: 5 },
      { Family: 'Blephariceridae', Score: 10 },
      { Family: 'Bothrioneurum iris', Score: 7 },
      { Family: 'Bothrioneurum vejdovskyanum', Score: 10 },
      { Family: 'Brachycentridae', Score: 8 },
      { Family: 'Branchiodrilus hortensis', Score: 5 },
      { Family: 'Branchiodrilus semperi', Score: 6 },
      { Family: 'Branchiura sowerbyi', Score: 2 },
      { Family: 'Brotia costula', Score: 7 },
      { Family: 'Caenidae', Score: 3 },
      { Family: 'Calamoceratidae', Score: 8 },
      { Family: 'Perlidae (calicneuria sp.)', Score: 10 },
      { Family: 'Calopterygidae', Score: 7 },
      { Family: 'Capniidae', Score: 10 },
      { Family: 'Caridina cf. nilotica', Score: 5 },
      { Family: 'Carychium minusculum', Score: 10 },
      { Family: 'Baetidae (centroptilum sp.)', Score: 8 },
      { Family: 'Ceratopogonidae', Score: 5 },
      { Family: 'Chaetogaster limnaei bengalensis', Score: 5 },
      { Family: 'Chaetogaster limnaei limnaei', Score: 5 },
      { Family: 'Chaetogaster langi', Score: 6 },
      { Family: 'Chironomidae', Score: 1 },
      { Family: 'Ephemerellidae (cincticostella sp.)', Score: 7 },
      { Family: 'Heptageniidae (cinygmina sp.)', Score: 7 },
      { Family: 'Clavidae', Score: 6 },
      { Family: 'Baetidae (cloedodes sp.)', Score: 7 },
      { Family: 'Coenagrionidae', Score: 5 },
      { Family: 'Corbicula assamensis', Score: 6 },
      { Family: 'Corbicula bensoni', Score: 8 },
      { Family: 'Corbicula cashmiriensis', Score: 5 },
      { Family: 'Corbicula striatella', Score: 4 },
      { Family: 'Corbiculidae', Score: 5 },
      { Family: 'Cordulegasteridae', Score: 9 },
      { Family: 'Corduliidae', Score: 5 },
      { Family: 'Corixidae', Score: 2 },
      { Family: 'Corydalidae', Score: 7 },
      { Family: 'Culicidae', Score: 2 },
      { Family: 'Cymothoidea', Score: 7 },
      { Family: 'Dendronereides heteropoda', Score: 6 },
      { Family: 'Dero cooperi', Score: 5 },
      { Family: 'Dendrodrilus rubidus', Score: 5 },
      { Family: 'Dero digitata', Score: 5 },
      { Family: 'Dero dorsalis', Score: 5 },
      { Family: 'Dero limosa', Score: 5 },
      { Family: 'Dero nivea', Score: 6 },
      { Family: 'Dero pectinata', Score: 6 },
      { Family: 'Dero sawayai', Score: 5 },
      { Family: 'Diamesinae (chronomidae)', Score: 8 },
      { Family: 'Digoniostoma cerameopoma', Score: 5 },
      { Family: 'Digoniostoma lithoglyphoides n. sp.', Score: 5 },
      { Family: 'Digoniostoma pulchella', Score: 5 },
      { Family: 'Dixidae', Score: 7 },
      { Family: 'Drawida nepalensis', Score: 6 },
      { Family: 'Ephemerellidae (drunella sp.)', Score: 10 },
      { Family: 'Dryopidae', Score: 10 },
      { Family: 'Ecnomidae', Score: 3 },
      { Family: 'Eisenia fetida', Score: 5 },
      { Family: 'Eiseniella tetraedra', Score: 8 },
      { Family: 'Heptageniidae (electrogena sp.)', Score: 6 },
      { Family: 'Ellobiidae (brackish water)', Score: 6 },
      { Family: 'Ellobiidae (freshwater: now carychiidae)', Score: 10 },
      { Family: 'Elmidae', Score: 10 },
      { Family: 'Empididae', Score: 4 },
      { Family: 'Enchytraeidae', Score: 9 },
      { Family: 'Heptageniidae (epeorus bispinosus)', Score: 8 },
      { Family: 'Heptageniidae (epeorus rhithralis)', Score: 10 },
      { Family: 'Ephemerellidae', Score: 6 },
      { Family: 'Ephemeridae', Score: 7 },
      { Family: 'Epiophlebiidae', Score: 10 },
      { Family: 'Erhaia banepaensis n. sp.', Score: 10 },
      { Family: 'Erhaia chandeshwariensis n. sp.', Score: 10 },
      { Family: 'Erpobdella srinagarensis n. sp.', Score: 7 },
      { Family: 'Erpobdellidae', Score: 4 },
      { Family: 'Euphaeidae', Score: 8 },
      { Family: 'Leptophlebiidae (euthraulus sp.)', Score: 5 },
      { Family: 'Ferrissia baconi', Score: 6 },
      { Family: 'Ferrissia verruca', Score: 6 },
      { Family: 'Fredericellidae', Score: 7 },
      { Family: 'Fridericia perrieri', Score: 9 },
      { Family: 'Gabbia orcula', Score: 5 },
      { Family: 'Gabbia stenothyroides', Score: 5 },
      { Family: 'Galba simulans', Score: 8 },
      { Family: 'Galba truncatula', Score: 8 },
      { Family: 'Gammaridae', Score: 8 },
      { Family: 'Gammarus aff. lacustris', Score: 8 },
      { Family: 'Gangetia miliacea', Score: 9 },
      { Family: 'Gerridae', Score: 4 },
      { Family: 'Glossiphonia complanata', Score: 4 },
      { Family: 'Glossiphoniidae', Score: 4 },
      { Family: 'Glossosomatidae', Score: 9 },
      { Family: 'Glyphidrilus gangeticus', Score: 7 },
      { Family: 'Goeridae', Score: 7 },
      { Family: 'Gordiidae', Score: 10 },
      { Family: 'Grapsidae', Score: 4 },
      { Family: 'Gyraulus convexiusculus', Score: 4 },
      { Family: 'Gyraulus euphraticus', Score: 4 },
      { Family: 'Gyraulus labiatus', Score: 5 },
      { Family: 'Gyrinidae', Score: 7 },
      { Family: 'Leptophlebiidae (habrophleboides sp.)', Score: 9 },
      { Family: 'Haemadipsa sylvestris', Score: 8 },
      { Family: 'Haemadipsa zeylanica agilis', Score: 8 },
      { Family: 'Haemadipsa zeylanica montevindicis', Score: 8 },
      { Family: 'Haemadipsidae', Score: 8 },
      { Family: 'Haemonais waldvogeli', Score: 7 },
      { Family: 'Haemopidae', Score: 8 },
      { Family: 'Helicopsychidae', Score: 9 },
      { Family: 'Helobdella stagnalis', Score: 7 },
      { Family: 'Hemiclepsis marginata asiatica', Score: 4 },
      { Family: 'Heptageniidae', Score: 7 },
      { Family: 'Himalayapotamon atkinsonianum', Score: 8 },
      { Family: 'Himalayapotamon emphysetum', Score: 8 },
      { Family: 'Himalayapotamon spec.', Score: 9 },
      { Family: 'Hippeutis umbilicalis', Score: 4 },
      { Family: 'Hirudinaria manillensis', Score: 8 },
      { Family: 'Hirudinidae', Score: 7 },
      { Family: 'Hydracarina', Score: 7 },
      { Family: 'Hydraenidae', Score: 7 },
      { Family: 'Hydrobiosidae', Score: 9 },
      { Family: 'Hydrometridae', Score: 6 },
      { Family: 'Hydropsychidae', Score: 3 },
      { Family: 'Hydroptilidae', Score: 4 },
      { Family: 'Hymenicoides carteri', Score: 8 },
      { Family: 'Hymenosomatidae', Score: 8 },
      { Family: 'Idiopoma dissimilis', Score: 6 },
      { Family: 'Ilyodrilus templetoni (southern)', Score: 5 },
      { Family: 'Indoplanorbis exustus', Score: 4 },
      { Family: 'Isonychiidae', Score: 5 },
      { Family: 'Lamellidens  phenchooganjensis', Score: 6 },
      { Family: 'Lamellidens consobrinus', Score: 7 },
      { Family: 'Lamellidens corrianus', Score: 7 },
      { Family: 'Lamellidens jenkinsianus', Score: 6 },
      { Family: 'Lamellidens lamellatus', Score: 8 },
      { Family: 'Lamellidens mainwaringi', Score: 7 },
      { Family: 'Lamellidens marginalis', Score: 6 },
      { Family: 'Lamellidens narainporensis', Score: 6 },
      { Family: 'Lamellidens rhadineus', Score: 6 },
      { Family: 'Lamellidens spec.', Score: 6 },
      { Family: 'Lepidostomatidae', Score: 7 },
      { Family: 'Leptophlebiidae', Score: 8 },
      { Family: 'Lestidae', Score: 8 },
      { Family: 'Leuctridae', Score: 10 },
      { Family: 'Libellulidae', Score: 3 },
      { Family: 'Limnephilidae', Score: 5 },
      { Family: 'Limnocentropodidae', Score: 9 },
      { Family: 'Limnodrilus claparedeanus', Score: 4 },
      { Family: 'Limnodrilus hoffmeisteri', Score: 2 },
      { Family: 'Limnodrilus udekemianus', Score: 4 },
      { Family: 'Limoniidae', Score: 8 },
      { Family: 'Lumbricidae', Score: 3 },
      { Family: 'Lumbriculidae', Score: 8 },
      { Family: 'Lumbriculus variegatus', Score: 8 },
      { Family: 'Lymnaea  kashmiriensis', Score: 6 },
      { Family: 'Lymnaea acuminata', Score: 4 },
      { Family: 'Lymnaeidae', Score: 4 },
      { Family: 'Macrobrachium spec.', Score: 4 },
      { Family: 'Marionina riparia', Score: 10 },
      { Family: 'Megascolecidae', Score: 7 },
      { Family: 'Mekongia crassa', Score: 6 },
      { Family: 'Melanoides pyramis', Score: 4 },
      { Family: 'Melanoides tuberculatus', Score: 4 },
      { Family: 'Metaphire houlleti', Score: 7 },
      { Family: 'Mermithidae', Score: 8 },
      { Family: 'Microchaetidae', Score: 7 },
      { Family: 'Chironomidae (microtendipes sp.)', Score: 4 },
      { Family: 'Monoligastridae', Score: 6 },
      { Family: 'Musculium goshaithanensis n. sp.', Score: 4 },
      { Family: 'Musculium indicum', Score: 4 },
      { Family: 'Myxobdella annandalei', Score: 10 },
      { Family: 'Myxobdella nepalica', Score: 10 },
      { Family: 'Naididae', Score: 6 },
      { Family: 'Nais alpina', Score: 10 },
      { Family: 'Nais bretscheri', Score: 6 },
      { Family: 'Nais communis', Score: 6 },
      { Family: 'Nais simplex', Score: 5 },
      { Family: 'Namalycastis fauveli', Score: 6 },
      { Family: 'Namalycastis indica', Score: 6 },
      { Family: 'Naucoridae', Score: 4 },
      { Family: 'Nemouridae', Score: 8 },
      { Family: 'Neoephemeridae', Score: 9 },
      { Family: 'Neoniphargus indicus', Score: 10 },
      { Family: 'Neorhynchoplax nasalis', Score: 8 },
      { Family: 'Nephthydae', Score: 8 },
      { Family: 'Nephthys oligobranchia', Score: 8 },
      { Family: 'Nephthys polybranchia', Score: 8 },
      { Family: 'Nepidae', Score: 4 },
      { Family: 'Nereidae', Score: 6 },
      { Family: 'Nereis chilkaensis', Score: 6 },
      { Family: 'Neritidae', Score: 8 },
      { Family: 'Neritina (dostia) violacea', Score: 8 },
      { Family: 'Neritina smithi', Score: 8 },
      { Family: 'Niphargidae', Score: 10 },
      { Family: 'Heptageniidae (notocanthurus cristatus)', Score: 7 },
      { Family: 'Notonectidae', Score: 3 },
      { Family: 'Novaculidae', Score: 8 },
      { Family: 'Novaculina gangetica', Score: 8 },
      { Family: 'Odontoceridae', Score: 8 },
      { Family: 'Onchidiidae', Score: 8 },
      { Family: 'Onchidium typhae', Score: 8 },
      { Family: 'Oosthuizobdella garoui', Score: 7 },
      { Family: 'Ozobranchidae', Score: 8 },
      { Family: 'Ozobranchus shipleyi', Score: 8 },
      { Family: 'Palaemonidae', Score: 7 },
      { Family: 'Paludinella (schuettiella) daengswangi', Score: 6 },
      { Family: 'Paludomus blanfordiana', Score: 7 },
      { Family: 'Paludomus conica', Score: 7 },
      { Family: 'Paraclepsis praedatrix', Score: 7 },
      { Family: 'Parathelphusidae', Score: 5 },
      { Family: 'Parreysia corrugata laevirostris', Score: 7 },
      { Family: 'Parreysia favidens', Score: 7 },
      { Family: 'Parreysia sikkimensis', Score: 7 },
      { Family: 'Parreysia viridula', Score: 7 },
      { Family: 'Peltoperlidae', Score: 10 },
      { Family: 'Perionyx excavatus', Score: 7 },
      { Family: 'Perlidae', Score: 9 },
      { Family: 'Perlodidae', Score: 9 },
      { Family: 'Philopotamidae', Score: 8 },
      { Family: 'Phryganeidae', Score: 8 },
      { Family: 'Physa (haitia) mexicana', Score: 2 },
      { Family: 'Physidae', Score: 2 },
      { Family: 'Phytia plicata', Score: 8 },
      { Family: 'Pila globosa', Score: 4 },
      { Family: 'Pisidium annandalei', Score: 9 },
      { Family: 'Pisidium atkinsonianum', Score: 8 },
      { Family: 'Pisidium casertanum', Score: 10 },
      { Family: 'Pisidium clarkeanum dhulikhelensis n. ssp.', Score: 6 },
      { Family: 'Pisidium clarkeanum', Score: 4 },
      { Family: 'Pisidium ellisi', Score: 10 },
      { Family: 'Pisidium kuiperi', Score: 9 },
      { Family: 'Pisidium nevllianum', Score: 5 },
      { Family: 'Pisidium prasongi', Score: 9 },
      { Family: 'Placobdelloides fulvus', Score: 4 },
      { Family: 'Placobdelloides multistriatus', Score: 7 },
      { Family: 'Planariidae', Score: 9 },
      { Family: 'Planorbidae', Score: 4 },
      { Family: 'Platorchestia platensis', Score: 8 },
      { Family: 'Platycnemididae', Score: 8 },
      { Family: 'Pleidae', Score: 4 },
      { Family: 'Pleuroceridae', Score: 7 },
      { Family: 'Plumatellidae', Score: 6 },
      { Family: 'Plumatella casmiana', Score: 6 },
      { Family: 'Poecilobdella granulosa', Score: 7 },
      { Family: 'Polycentropodidae', Score: 3 },
      { Family: 'Chironomidae (polypedilum sp.)', Score: 4 },
      { Family: 'Pomatiopsidae', Score: 10 },
      { Family: 'Potamidae', Score: 9 },
      { Family: 'Pristina acuminata', Score: 6 },
      { Family: 'Pristina cf. biserrata', Score: 6 },
      { Family: 'Pristina synclites', Score: 6 },
      { Family: 'Protoneuridae', Score: 8 },
      { Family: 'Psephenidae', Score: 8 },
      { Family: 'Psychodidae (black)', Score: 6 },
      { Family: 'Psychodidae (white)', Score: 1 },
      { Family: 'Pyralidae', Score: 8 },
      { Family: 'Radiatula andersoniana', Score: 8 },
      { Family: 'Radiatula bonneaudi', Score: 8 },
      { Family: 'Radiatula caerulea', Score: 6 },
      { Family: 'Radiatula gaudichaudi', Score: 6 },
      { Family: 'Radiatula keraudreni', Score: 7 },
      { Family: 'Radiatula lima', Score: 7 },
      { Family: 'Radiatula occata', Score: 7 },
      { Family: 'Radiatula olivaria', Score: 8 },
      { Family: 'Radiatula pachysoma', Score: 7 },
      { Family: 'Radiatula shurtleffiania', Score: 7 },
      { Family: 'Radix brevicauda', Score: 5 },
      { Family: 'Radix hookeri', Score: 8 },
      { Family: 'Radix luteola', Score: 4 },
      { Family: 'Radix ovalis', Score: 4 },
      { Family: 'Radix persica', Score: 4 },
      { Family: 'Rhithrogena nepalensis', Score: 10 },
      { Family: 'Rhitrogena sp.', Score: 8 },
      { Family: 'Rhyacophilidae', Score: 6 },
      { Family: 'Salifa (herpobdelloidea) lateroculata', Score: 5 },
      { Family: 'Salifa (nematobdella) biharensis', Score: 6 },
      { Family: 'Salifidae', Score: 3 },
      { Family: 'Sartoriana spinigera', Score: 5 },
      { Family: 'Scaphula celox', Score: 8 },
      { Family: 'Scaphula deltae', Score: 8 },
      { Family: 'Scirtidae', Score: 10 },
      { Family: 'Segmentina calatha', Score: 4 },
      { Family: 'Segmentina trochoidea', Score: 5 },
      { Family: 'Septaria tesselata', Score: 8 },
      { Family: 'Septariidae', Score: 8 },
      { Family: 'Sericostomatidae', Score: 6 },
      { Family: 'Sermyla riqueti', Score: 4 },
      { Family: 'Simuliidae', Score: 5 },
      { Family: 'Siphlonuridae', Score: 10 },
      { Family: 'Sisyridae', Score: 8 },
      { Family: 'Sphaeriidae', Score: 5 },
      { Family: 'Spongillidae', Score: 7 },
      { Family: 'Stenopsychidae', Score: 7 },
      { Family: 'Stenothyra deltae', Score: 8 },
      { Family: 'Stenothyra monilifera', Score: 8 },
      { Family: 'Stenothyra nana', Score: 8 },
      { Family: 'Stenothyra ornata', Score: 8 },
      { Family: 'Stenothyridae', Score: 8 },
      { Family: 'Stratiomyidae', Score: 4 },
      { Family: 'Stylaria fossularis', Score: 6 },
      { Family: 'Succinea cf. daucina', Score: 5 },
      { Family: 'Succineidae', Score: 5 },
      { Family: 'Tabanidae', Score: 4 },
      { Family: 'Taeniopterygidae', Score: 10 },
      { Family: 'Talitridae', Score: 8 },
      { Family: 'Thiara granifera', Score: 4 },
      { Family: 'Thiara lineata', Score: 4 },
      { Family: 'Thiara scabra', Score: 5 },
      { Family: 'Thiaridae', Score: 4 },
      { Family: 'Thremmatidae', Score: 8 },
      { Family: 'Tipulidae', Score: 7 },
      { Family: 'Ephemerellidae (torleya nepalica)', Score: 6 },
      { Family: 'Tricula godawariensis n. sp.', Score: 10 },
      { Family: 'Tricula montana', Score: 10 },
      { Family: 'Tubificidae', Score: 2 },
      { Family: 'Tylenchida', Score: 4 },
      { Family: 'Uenoidae', Score: 9 },
      { Family: 'Unionidae', Score: 5 },
      { Family: 'Grapsidae (varuna littorata)', Score: 4 },
      { Family: 'Veliidae', Score: 8 },
      { Family: 'Viviparidae', Score: 6 },
      { Family: 'Whitmania laevis', Score: 8 }
    ],
    HKHbios: [
      { Family: 'Dugesidae', Score: 4 },
      { Family: 'Nematoda', Score: 2 },
      { Family: 'Pila', Score: 6 },
      { Family: 'Assimineidae', Score: 6 },
      { Family: 'Bithyniidae', Score: 5 },
      { Family: 'Lymnaeidae', Score: 4 },
      { Family: 'Neritidae', Score: 8 },
      { Family: 'Onchidium', Score: 8 },
      { Family: 'Physidae', Score: 2 },
      { Family: 'Planorbidae', Score: 6 },
      { Family: 'Gyraulus (labiatus)', Score: 6 },
      { Family: 'Gyraulus (convexicusculus)', Score: 6 },
      { Family: 'Pleuroceridae', Score: 6 },
      { Family: 'Pomatiopsidae', Score: 8 },
      { Family: 'Stenothyridae', Score: 8 },
      { Family: 'Succineidae', Score: 5 },
      { Family: 'Thiaridae', Score: 4 },
      { Family: 'Viviparidae', Score: 6 },
      { Family: 'Arcidae', Score: 8 },
      { Family: 'Corbiculidae', Score: 4 },
      { Family: 'Psammobiidae', Score: 8 },
      { Family: 'Sphaeriidae', Score: 6 },
      { Family: 'Pisidium', Score: 7 },
      { Family: 'Unionidae', Score: 6 },
      { Family: 'Lamellidens', Score: 5 },
      { Family: 'Nephthyidae', Score: 5 },
      { Family: 'Nereididae', Score: 6 },
      { Family: 'Lumbricidae', Score: 5 },
      { Family: 'Megascolecidae', Score: 6 },
      { Family: 'Microchaetidae', Score: 7 },
      { Family: 'Naididae', Score: 3 },
      { Family: 'Oligochaeta', Score: 2 },
      { Family: 'Tubificidae', Score: 1 },
      { Family: 'Glossiphoniidae', Score: 4 },
      { Family: 'Salifidae', Score: 3 },
      { Family: 'Atyidae', Score: 6 },
      { Family: 'Cirolanidae', Score: 8 },
      { Family: 'Cymothoidae', Score: 5 },
      { Family: 'Hymenosomatidae', Score: 8 },
      { Family: 'Mysidae', Score: 6 },
      { Family: 'Neoniphargidae', Score: 10 },
      { Family: 'Palaemonidae', Score: 6 },
      { Family: 'Parathelphusidae', Score: 6 },
      { Family: 'Potamidae', Score: 7 },
      { Family: 'Talitridae', Score: 8 },
      { Family: 'Ameletidae', Score: 10 },
      { Family: 'Baetiella', Score: 8 },
      { Family: 'Baetis', Score: 9 },
      { Family: 'Cloenoninae', Score: 5 },
      { Family: 'Platybaetis', Score: 8 },
      { Family: 'Caenidae', Score: 7 },
      { Family: 'Brachycercus', Score: 10 },
      { Family: 'Caenis', Score: 7 },
      { Family: 'Ephemerellidae', Score: 7 },
      { Family: 'Cincticostella', Score: 10 },
      { Family: 'Ephacerella', Score: 8 },
      { Family: 'Torleya', Score: 7 },
      { Family: 'Ephemera', Score: 10 },
      { Family: 'Epiophlebia', Score: 10 },
      { Family: 'Heptageniidae', Score: 10 },
      { Family: 'Ecdyonurus', Score: 10 },
      { Family: 'Epeorus', Score: 10 },
      { Family: 'Iron', Score: 9 },
      { Family: 'Rhithrogena', Score: 10 },
      { Family: 'Isonychiidae', Score: 10 },
      { Family: 'Leptophlebiidae', Score: 7 },
      { Family: 'Euthraulus', Score: 10 },
      { Family: 'Potamanthellus', Score: 10 },
      { Family: 'Palingeniidae', Score: 10 },
      { Family: 'Potamanthidae', Score: 10 },
      { Family: 'Prosopistoma', Score: 10 },
      { Family: 'Aeshnidae', Score: 7 },
      { Family: 'Amphipterygidae', Score: 7 },
      { Family: 'Calopterygidae', Score: 8 },
      { Family: 'Chlorocyphidae', Score: 6 },
      { Family: 'Coenagrionidae', Score: 5 },
      { Family: 'Cordulegasteridae', Score: 10 },
      { Family: 'Corduliidae', Score: 5 },
      { Family: 'Macromia', Score: 7 },
      { Family: 'Euphaeidae', Score: 9 },
      { Family: 'Lestidae', Score: 7 },
      { Family: 'Libellulidae', Score: 6 },
      { Family: 'Megapodagrionidae', Score: 10 },
      { Family: 'Platycnemidae', Score: 7 },
      { Family: 'Protoneuridae', Score: 5 },
      { Family: 'Synlestidae', Score: 9 },
      { Family: 'Chloroperlidae', Score: 9 },
      { Family: 'Leuctridae', Score: 10 },
      { Family: 'Nemouridae', Score: 9 },
      { Family: 'Indonemoura', Score: 10 },
      { Family: 'Mesonemoura', Score: 9 },
      { Family: 'Perlidae', Score: 8 },
      { Family: 'Aphelocheirus', Score: 9 },
      { Family: 'Sigara', Score: 6 },
      { Family: 'Hebridae', Score: 7 },
      { Family: 'Mesoveliidae', Score: 6 },
      { Family: 'Naucoridae', Score: 7 },
      { Family: 'Nepidae', Score: 6 },
      { Family: 'Notonectidae', Score: 3 },
      { Family: 'Corydalidae', Score: 7 },
      { Family: 'Sisyridae', Score: 7 },
      { Family: 'Chrysomelidae', Score: 8 },
      { Family: 'Dryopidae', Score: 5 },
      { Family: 'Elmidae', Score: 8 },
      { Family: 'Eulichadidae', Score: 8 },
      { Family: 'Gyrinidae', Score: 7 },
      { Family: 'Haliplidae', Score: 6 },
      { Family: 'Hydraenidae', Score: 8 },
      { Family: 'Noteridae', Score: 4 },
      { Family: 'Psephenidae', Score: 8 },
      { Family: 'Eubrianacinae', Score: 9 },
      { Family: 'Eubriinae', Score: 8 },
      { Family: 'Psephenoidinae', Score: 8 },
      { Family: 'Scirtidae', Score: 8 },
      { Family: 'Apatanidae', Score: 9 },
      { Family: 'Brachycentridae', Score: 8 },
      { Family: 'Brachycentrus', Score: 6 },
      { Family: 'Micrasema', Score: 10 },
      { Family: 'Dipseudopsidae', Score: 5 },
      { Family: 'Encomus', Score: 6 },
      { Family: 'Glossosomatidae', Score: 8 },
      { Family: 'Agapetinae', Score: 9 },
      { Family: 'Glossosoma', Score: 8 },
      { Family: 'Goeridae', Score: 9 },
      { Family: 'Helicopsychidae', Score: 10 },
      { Family: 'Hydropsychidae', Score: 9 },
      { Family: 'Hydroptilidae', Score: 9 },
      { Family: 'Lepidostomatidae', Score: 8 },
      { Family: 'Odontoceridae', Score: 7 },
      { Family: 'Marilia', Score: 7 },
      { Family: 'Philopotamidae', Score: 7 },
      { Family: 'Pseudoneureclipsis', Score: 8 },
      { Family: 'Psychomyiidae', Score: 7 },
      { Family: 'Rhyacophilidae', Score: 8 },
      { Family: 'Stenopsyche', Score: 8 },
      { Family: 'Uenoidae', Score: 10 },
      { Family: 'Pyralidae', Score: 7 },
      { Family: 'Athericidae', Score: 9 },
      { Family: 'Ceratopogonidae type bezzia', Score: 2 },
      { Family: 'Chironomiade', Score: 1 },
      { Family: 'Diamesinl', Score: 8 },
      { Family: 'Orthocladiinae', Score: 8 },
      { Family: 'Tanytarsini', Score: 4 },
      { Family: 'Deuterophlebiidae', Score: 8 },
      { Family: 'Dolichopodidae', Score: 2 },
      { Family: 'Empididae', Score: 8 },
      { Family: 'Ephyridae', Score: 1 },
      { Family: 'Limoniidae', Score: 8 },
      { Family: 'Cf. antocha', Score: 8 },
      { Family: 'Muscidae', Score: 1 },
      { Family: 'Pediciidae', Score: 8 },
      { Family: 'Cf. dicranot', Score: 8 },
      { Family: 'Psychodidae black', Score: 6 },
      { Family: 'Psychodidae white', Score: 1 },
      { Family: 'Rhagionidae', Score: 9 },
      { Family: 'Sciaridae', Score: 6 },
      { Family: 'Sciomyzidae', Score: 8 },
      { Family: 'Simuliidae', Score: 7 },
      { Family: 'Syrphidae', Score: 1 },
      { Family: 'Tabanidae', Score: 7 },
      { Family: 'Tipulidae', Score: 8 },
      { Family: 'Lophopodidae', Score: 7 },
      { Family: 'Plumatellidae', Score: 7 }
    ],
    SingScore: [
      { Family: 'Corixidae', Score: 10 },
      { Family: 'Gerridae', Score: 5 },
      { Family: 'Helotrephidae', Score: 4 },
      { Family: 'Nereididae', Score: 6 },
      { Family: 'Mesoveliidae', Score: 10 },
      { Family: 'Naucoridae', Score: 7 },
      { Family: 'Notonectidae', Score: 8 },
      { Family: 'Tubificidae', Score: 2 },
      { Family: 'Veliidae', Score: 7 },
      { Family: 'Erpobdellidae', Score: 1 },
      { Family: 'Sialidae', Score: 8 },
      { Family: 'Glossiphoniidae', Score: 2 },
      { Family: 'Haemadipsidae', Score: 5 },
      { Family: 'Calamoceratidae', Score: 9 },
      { Family: 'Ecnomidae', Score: 6 },
      { Family: 'Ampullariidae', Score: 3 },
      { Family: 'Hydropsychidae', Score: 7 },
      { Family: 'Ancylidae', Score: 1 },
      { Family: 'Hydroptilidae', Score: 6 },
      { Family: 'Bithyniidae', Score: 3 },
      { Family: 'Leptoceridae', Score: 7 },
      { Family: 'Lymnaeida', Score: 1 },
      { Family: 'Odontoceridae', Score: 10 },
      { Family: 'Physidae', Score: 2 },
      { Family: 'Philopotamidae', Score: 8 },
      { Family: 'Planorbidae', Score: 2 },
      { Family: 'Polycentropodidae', Score: 9 },
      { Family: 'Thiaridae', Score: 1 },
      { Family: 'Crambidae', Score: 5 },
      { Family: 'Amphipoda', Score: 2 },
      { Family: 'Atyidae', Score: 6 },
      { Family: 'Copepoda', Score: 4 },
      { Family: 'Curculionidae', Score: 6 },
      { Family: 'Isopoda', Score: 1 },
      { Family: 'Dytiscidae', Score: 5 },
      { Family: 'Ostracoda', Score: 3 },
      { Family: 'Hydraenidae', Score: 8 },
      { Family: 'Palaemonidae', Score: 7 },
      { Family: 'Hydrophilidae', Score: 6 },
      { Family: 'Parathelphusidae', Score: 9 },
      { Family: 'Scirtidae', Score: 8 },
      { Family: 'Amphipterygidae', Score: 10 },
      { Family: 'Athericidae', Score: 10 },
      { Family: 'Calopterygidae', Score: 8 },
      { Family: 'Canacidae', Score: 6 },
      { Family: 'Coenagrionidae', Score: 3 },
      { Family: 'Ceratopogonidae', Score: 3 },
      { Family: 'Euphaeidae', Score: 9 },
      { Family: 'Chironomidae', Score: 2 },
      { Family: 'Platycnemididae', Score: 5 },
      { Family: 'Corethrellidae', Score: 10 },
      { Family: 'Platystictidae', Score: 8 },
      { Family: 'Culicidae', Score: 1 },
      { Family: 'Dolichopodidae', Score: 1 },
      { Family: 'Empididae', Score: 4 },
      { Family: 'Aeshnidae', Score: 9 },
      { Family: 'Ephydridae', Score: 4 },
      { Family: 'Corduliidae', Score: 5 },
      { Family: 'Muscidae', Score: 6 },
      { Family: 'Gomphidae', Score: 8 },
      { Family: 'Psychodidae', Score: 2 },
      { Family: 'Libellulidae', Score: 4 },
      { Family: 'Simuliidae', Score: 7 },
      { Family: 'Syrphidae', Score: 4 },
      { Family: 'Tipulidae', Score: 3 },
      { Family: 'Baetidae', Score: 7 },
      { Family: 'Caenidae', Score: 7 },
      { Family: 'Collembola', Score: 5 },
      { Family: 'Heptageniidae', Score: 9 },
      { Family: 'Leptophlebiidae', Score: 10 },
      { Family: 'Acari', Score: 4 },
      { Family: 'Leuctridae', Score: 10 },
      { Family: 'Perlidae', Score: 9 }
    ],
  }
